<?php

namespace App\Services\Ai;

/**
 * Deterministic in-memory AI provider — the default when BUILD_AI_PROVIDER=mock
 * or when no real provider is configured. Produces plausible fixtures so the
 * whole workflow (plan -> approval -> code -> commit) can be exercised
 * end-to-end without hitting any external service.
 */
class MockProvider implements AiProviderInterface
{
    public function name(): string
    {
        return 'mock';
    }

    public function isConfigured(): bool
    {
        return true;
    }

    public function analyzeRequirement(string $requirement, array $context = []): array
    {
        $summary = substr(preg_replace('/\s+/', ' ', trim($requirement)) ?? '', 0, 160);

        $lower = strtolower($requirement);
        $type = 'task';
        if (str_contains($lower, 'bug') || str_contains($lower, 'fix'))     { $type = 'bug'; }
        if (str_contains($lower, 'feature') || str_contains($lower, 'add')) { $type = 'feature'; }
        if (str_contains($lower, 'refactor'))                                { $type = 'refactor'; }
        if (str_contains($lower, 'ui') || str_contains($lower, 'style'))     { $type = 'ui_fix'; }
        if (str_contains($lower, 'security'))                                { $type = 'security'; }

        $risk = 'medium';
        if (str_contains($lower, 'production') || str_contains($lower, 'urgent') || str_contains($lower, 'security')) {
            $risk = 'high';
        }

        return [
            'summary'                => $summary !== '' ? $summary : 'Unspecified requirement.',
            'likely_files'           => [],
            'suggested_request_type' => $type,
            'suggested_priority'     => str_contains($lower, 'urgent') ? 'urgent' : 'normal',
            'suggested_risk_level'   => $risk,
            'notes'                  => 'Generated by MockProvider — no external AI call was made.',
            'raw'                    => ['provider' => 'mock'],
        ];
    }

    public function preparePlan(string $requirement, array $context = []): array
    {
        return [
            'summary'         => 'Plan generated by MockProvider (deterministic scaffold).',
            'steps'           => [
                ['kind' => 'inspect', 'note' => 'Read repo metadata + relevant files.'],
                ['kind' => 'plan',    'note' => 'Draft file changes and tests without touching disk.'],
                ['kind' => 'code',    'note' => 'Emit patch after superadmin code-approval.'],
                ['kind' => 'test',    'note' => 'Run relevant test suites; block on failure.'],
                ['kind' => 'commit',  'note' => 'Create commit on working branch after commit-approval.'],
                ['kind' => 'pr',      'note' => 'Open PR after pr-approval.'],
            ],
            'test_plan'       => [
                ['kind' => 'unit', 'note' => 'Run vendor/bin/phpunit / npm test on affected paths.'],
            ],
            'files_estimated' => [],
            'risk_level'      => 'medium',
            'tokens_used'     => 0,
            'raw'             => ['provider' => 'mock'],
        ];
    }

    public function generateCodeChanges(array $plan, array $context = []): array
    {
        return [
            'summary'     => 'No code changes generated — MockProvider is a placeholder for development.',
            'files'       => [],
            'tokens_used' => 0,
            'raw'         => ['provider' => 'mock'],
        ];
    }

    public function summarizeDiff(string $diffText, array $context = []): array
    {
        $len = strlen($diffText);
        return [
            'summary'     => $len === 0 ? '(no diff)' : "Diff of {$len} characters.",
            'tokens_used' => 0,
        ];
    }
}
